name: mohamed222348_expense_tracker
description: "mohamed222348 - BUE ICS Mobile Development Module (Individual Project)"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.5
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2
  gradient_borders: ^1.0.0
  font_awesome_flutter: ^10.6.0

  get: ^4.6.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/BudgetBuddyLogo.png
